config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin', to: 'admin/portfolios#index'
  namespace :admin do
    resources :portfolios do
      resources :pages, shallow: true do
        resources :blocks, shallow: true do
          resources :elements, shallow: true
        end
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
# frozen_string_literal: true

##
# This class represents a block of elements in a page
class Block < ApplicationRecord
  belongs_to :page
  has_many :elements, dependent: :destroy
end

app/models/element.rb
# frozen_string_literal: true

##
# This class represents an element in a block
class Element < ActiveRecord::Base
  belongs_to :block

  attr_accessor :weight

  AVAILABLE_TYPES = [:link].freeze
end

app/models/element/link.rb
# frozen_string_literal: true

class Element
  ##
  # This class represents a link element
  class Link < ApplicationRecord
    belongs_to :element

    delegate :weight, to: :element
    delegate :block, to: :element
  end
end

app/models/elements/link.rb
# frozen_string_literal: true

module Elements
  ##
  # This class represents a link element
  class Link < ActiveRecord::Base
    belongs_to :element

    delegate :weight, to: :element
    delegate :block, to: :element
  end
end

app/models/page.rb
# frozen_string_literal: true

##
# This class represents a page on a portfolio
class Page < ApplicationRecord
  has_many :blocks, dependent: :destroy
  belongs_to :portfolio

  def ordered_blocks
    blocks.order(:weight)
  end
end

app/models/portfolio.rb
# frozen_string_literal: true

##
# This class represents a portfolio
class Portfolio < ApplicationRecord
  has_many :pages, dependent: :destroy
end

app/controllers/admin/blocks_controller.rb
# frozen_string_literal: true

module Admin
  class BlocksController < ApplicationController
    def new
      render 'new', locals: { block: ::Block.new }
    end

    def create
      ::Block.create(filtered_params.merge(page_id: params[:page_id]))
      redirect_to edit_admin_page_path(params[:page_id])
    end

    def edit
      render 'edit', locals: { block: block }
    end

    def update
      block.update(filtered_params)
      redirect_to edit_admin_block_path(block)
    end

    def destroy
      page_id = block.page.id
      block.destroy
      redirect_to edit_admin_page_path(page_id)
    end

    private

    def blocks
      @blocks ||= find_blocks
    end

    def find_blocks
      return ::Block.all if params['page_id'].blank?
      ::Page.find(params['page_id']).blocks
    end

    def block
      @block ||= find_block
    end

    def find_block
      ::Block.find(params['id']) if params['id']
    end

    def filtered_params
      params[:block].permit(:weight, :page_id)
    end
  end
end

app/controllers/admin/elements_controller.rb
module Admin
  class ElementsController < ApplicationController
    def new
      render 'new', locals: { element: Element.new(block_id: block.id) }
    end

    private

    def block
      @block ||= Block.find(params[:block_id])
    end
  end
end

app/controllers/admin/pages_controller.rb
# frozen_string_literal: true

module Admin
  class PagesController < ApplicationController
    def new
      render 'new', locals: { page: ::Page.new }
    end

    def create
      ::Page.create(filtered_params.merge(portfolio_id: params[:portfolio_id]))
      redirect_to edit_admin_portfolio_path(params[:portfolio_id])
    end

    def edit
      render 'edit', locals: { page: page }
    end

    def update
      page.update(filtered_params)
      redirect_to edit_admin_page_path(page)
    end

    def destroy
      page.destroy
      redirect_to admin_path
    end

    private

    def pages
      @pages ||= find_pages
    end

    def find_pages
      return ::Page.all if params['portfolio_id'].blank?
      ::Portfolio.find(params['portfolio_id']).pages
    end

    def page
      @page ||= find_page
    end

    def find_page
      ::Page.find(params['id']) if params['id']
    end

    def filtered_params
      params[:page].permit(:name, :portfolio_id)
    end
  end
end

app/controllers/admin/portfolio_controller.rb
module Admin
  class PortfolioController < ApplicationController
    def index
      render 'index', locals: { portfolios: portfolios }
    end

    def new; end

    def create
      Portfolio.create(filtered_params)
      redirect_to admin_path
    end

    def show
      render 'show', locals: { portfolio: portfolio }
    end

    def edit
      render 'edit', locals: { portfolio: portfolio }
    end

    def update
      portfolio.update(filtered_params)
      redirect_to edit_admin_portfolio_path(portfolio)
    end

    def destroy
      portfolio.destroy
      redirect_to admin_path
    end

    private

    def portfolios
      Portfolio.all
    end

    def portfolio
      Portfolio.find(params['id'])
    end

    def filtered_params
      params[:portfolio].permit(:name, :description)
    end
  end
end

app/controllers/admin/portfolios_controller.rb
# frozen_string_literal: true

module Admin
  class PortfoliosController < ApplicationController
    def index
      render 'index', locals: { portfolios: portfolios }
    end

    def new
      render 'new', locals: { portfolio: ::Portfolio.new }
    end

    def create
      ::Portfolio.create(filtered_params)
      redirect_to admin_path
    end

    def edit
      render 'edit', locals: { portfolio: portfolio }
    end

    def update
      portfolio.update(filtered_params)
      redirect_to edit_admin_portfolio_path(portfolio)
    end

    def destroy
      portfolio.destroy
      redirect_to admin_path
    end

    private

    def portfolios
      ::Portfolio.all
    end

    def portfolio
      ::Portfolio.find(params['id'])
    end

    def pages
      @pages ||= portfolio.pages
    end

    def filtered_params
      params.require(:portfolio).permit(:name, :description)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/blocks/new.html.erb
<%= form_for(block, url: { action: :create }) do |f| %>
  <%= label_tag(:name, 'Weight') %>
  <%= f.text_field(:weight) %>
  <%= submit_tag('Create') %>
<% end %>

app/views/admin/elements/_link.html.erb
<%= label_tag 'Title' %>
<%= text_field_tag :title %>

app/views/admin/elements/new.html.erb
<%= form_for element, url: { action: :create } do |f| %>
  <%= label_tag(:name, 'Weight') %>
  <%= f.text_field(:weight) %>
  <%= render 'link' %>
  <%= submit_tag 'Create' %>
<% end %>

app/views/admin/pages/_block.html.erb
<fieldset>
  <legend><%= link_to '(X)', "/admin/blocks/#{block.id}", method: :delete, data: { confirm: 'Are you sure?' } %><%= link_to "Block #{block.id}", edit_admin_block_path(block) %> (weight: <%= block.weight %>)</legend>
  <%= render 'new_element', block: block %>
  <table>
    <tr>
      <% block.elements.each do |element| %>
        <%= render 'element', element: element %>
      <% end %>
    </tr>
  </table>
</fieldset>

app/views/admin/pages/_new_element.html.erb
<%= form_tag new_admin_block_element_path(block), method: :get do %>
  <%= select_tag 'element_type', options_for_select(Element::AVAILABLE_TYPES), prompt: 'Element type' %>
  <%= submit_tag "Add element" %>
<% end %>

app/views/admin/pages/edit.html.erb
<%= form_for(page, url: { action: :update }) do |f| %>
  <%= label_tag(:name, 'Name') %>
  <%= f.text_field(:name) %>
  <%= f.submit('Update') %>
<% end %>

<table>
  <tr>
    <th>Blocks (<%= link_to 'New', new_admin_page_block_path(page) %>)</th>
  </tr>
<% page.ordered_blocks.each do |block| %>
  <tr>
    <td>
      <%= render 'block', block: block %>
    </td>
  </tr>
<% end %>
</table>

<%= link_to 'Back', edit_admin_portfolio_path(page.portfolio) %>

app/views/admin/pages/new.html.erb
<%= form_for(page, url: { action: :create }) do |f| %>
  <%= label_tag(:name, 'Name') %>
  <%= f.text_field(:name) %>
  <%= submit_tag('Create') %>
<% end %>

app/views/admin/portfolios/edit.html.erb
<%= form_for(portfolio, url: admin_portfolio_path(portfolio), method: :put) do |f| %>
  <%= label_tag(:name, 'Name') %>
  <%= f.text_field(:name) %>
  <%= label_tag(:name, 'Description') %>
  <%= f.text_field(:description) %>
  <%= f.submit('Update') %>
<% end %>

<table>
  <tr>
    <th>Pages</th>
    <th><%= link_to 'Create', new_admin_portfolio_page_path(portfolio) %></th>
    <th></th>
  </tr>

<% portfolio.pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= link_to "Edit", edit_admin_page_path(page) %></td>
    <td><%= link_to "Remove", "/admin/pages/#{page.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Back', admin_path %>

app/views/admin/portfolios/index.html.erb
<h1>Welcome to the admin interface</h1>

<h2>Portfolios</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

<% portfolios.each do |portfolio| %>
  <tr>
    <td><%= portfolio.name %></td>
    <td><%= portfolio.description %></td>
    <td><%= link_to "Edit", edit_admin_portfolio_path(portfolio) %></td>
    <td><%= link_to "Remove", "/admin/portfolios/#{portfolio.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New portfolio', new_admin_portfolio_path %>

app/views/admin/portfolios/new.html.erb
<%= form_for(portfolio, url: {action: "create"}) do |f| %>
  <%= label_tag(:name, 'Name') %>
  <%= f.text_field(:name) %>
  <%= label_tag(:name, 'Description') %>
  <%= f.text_field(:description) %>
  <%= submit_tag('Create') %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>